[project]
name = "precivault"
authors = [
    { name = "Shubham Mishra", email = "shubham@preciholesports.com" }
]
description = "PreciVault is a top-tier password manager that securely stores your passwords with advanced encryption. It enhances your security with TOTP authentication and keeps your digital life safe and organized."
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

# Add your runtime dependencies here
dependencies = [
    "pyotp>=2.9.0",
    "cryptography>=42.0.0"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# Required for Frappe compatibility
[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<17.0.0"

# Optional: only installed in developer mode
[tool.bench.dev-dependencies]
pytest = "~=7.4.0"
semgrep = "==1.162.0"
