[project]
name = "precivault"
version = "0.0.1"
authors = [
    { name = "Shubham Mishra", email = "shubham@preciholesports.com"}
]
description = "PreciVault is a top-tier password manager that securely store your password with advance encryption. It enhances your security with TOTP authentication. PrecValult Keeps your digital life safe, organized."
requires-python = ">=3.10"
readme = "README.md"
#dynamic = ["version"]
dependencies = [
    #"frappe~=15.0.0" # Installed and managed by bench.
    "frappe>=15.0.0,<16.0.0"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

# These dependencies are only installed when developer mode is enabled
[tool.bench.dev-dependencies]
# package_name = "~=1.1.0"
